### ISSUE TITLE
Wrong service name in the docker-compose file

### ISSUE THREAD

**Issue by gcc-florda** [7574-sistemas-distribuidos/docker-from-docker#1]
In the `docker-compose.yml` file, the nginx service should be named `dockerfromdocker_nginx_1` for the main.py script to work properly:

```
nginx:
    image: nginx
    container_name: dockerfromdocker_nginx_1
    ports:
      - 10080:80
```
